matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8
    - os: linux
      language: android
      jdk: oraclejdk8
      sudo: required
      android:
        components:
          - platform-tools
          - tools
          - build-tools-25.0.0
          - build-tools-26.0.2
          - android-21
          - android-26
          - sys-img-armeabi-v7a-android-21
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
          - extra-android-support

cache:
  directories:
    - $HOME/.nvm
    - $HOME/.npm
    - $HOME/.cocoapods
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_cache: .travis/before-cache.sh
before_install: . .travis/before-install.sh
install: .travis/install.sh
before_script: .travis/before-ci.sh
script: .travis/ci.sh
